name: 'PR Status Labeller'
description: 'Auto-labels pull requests based on their status'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tag'
  color: 'green'
author: "Benjamin Nolan <benjamin.nolan@comnoco.io>"
